documentation related updates
fortinet/fortigate-autoscale-azure pull request #16
Opened 2021-04-23 00:24 UTC by JaydenLiang

this PR mainly resolve the issues addressed in #15 
targeting the planned release version: 3.3.0

2021-04-23 17:30 UTC, jamie-pate approved these changes

2021-05-13 17:22 UTC, klc178 requested changes
I also have additional change.s.

2021-05-13 21:08 UTC, JaydenLiang commented on templates/deploy_fortigate_autoscale.hybrid_licensing.json
> +FortiAnalyzer version supported by FortiGate Autoscale for Azure.
a correction was issued on its following commit.

2021-05-13 23:03 UTC, klc178 approved these changes

2021-05-13 23:14 UTC, merged