Feat module reference reorganization
fortinet/fortigate-autoscale-azure pull request #3
Opened 2021-03-16 23:21 UTC by JaydenLiang

2021-03-17 18:13 UTC, jamie-pate requested changes

2021-03-17 18:13 UTC, jamie-pate commented on webpack.config.js
> +    entry: {
I got this working with multiple entries... need to add entries and use `splitChunks` in the optimization section for webpack.

2021-03-17 22:44 UTC, JaydenLiang commented
@jamie-pate adding the entryPoint to each function solves the problem. much simpler. no need to slipt chunks now. thanks for pointing out the entryPoint method.

2021-03-17 23:03 UTC, jamie-pate requested changes

2021-03-17 23:03 UTC, jamie-pate commented on webpack.config.js
> +            return './[name]/index-bundle.js';
can reset this now

2021-03-17 23:03 UTC, jamie-pate commented on fgt-as-handler/function.json
> +    "scriptFile": "../dist/autoscale-shared/index-bundle.js",
just index.js ?

2021-03-18 22:01 UTC, jamie-pate requested changes

2021-03-18 22:01 UTC, jamie-pate commented on scripts/make-dist.ts
> +shelljs.rm('-f', fileFuncapp);
this could be `await rmdir(dirname, {recursive: true})`
`const { promises: { rmdir }} = require('fs');`

2021-03-19 18:53 UTC, jamie-pate approved these changes

2021-03-19 20:16 UTC, merged