staging proj 15397 enhancement
fortinet/fortigate-autoscale-azure pull request #61
Opened 2021-08-23 18:24 UTC by JaydenLiang

resolve #37
resolve #44
resolve #45
resolve #42
resolve #56
resolve #54
resolve #52
resolve #50
resolve #48

2021-08-23 21:34 UTC, Joel-Cripps reviewed
this uses the new core which has the changes for the vm termination correct?

2021-08-23 21:35 UTC, Joel-Cripps approved these changes

2021-08-23 23:36 UTC, jamie-pate requested changes

2021-08-23 23:36 UTC, jamie-pate commented on templates/deploy_fortigate_autoscale.hybrid_licensing.json
> +                "description": "The VMSS placement group options. For mor information, please see: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-ava
mor(e)

2021-09-20 18:34 UTC, jamie-pate approved these changes

2021-11-19 21:17 UTC, merged